<?php
declare(strict_types=1);

namespace Plaisio;

/**
 * Class for holding all constants generated by PhpStratum.
 */
class C
{
  //--------------------------------------------------------------------------------------------------------------------
  /**
   * @setbased.stratum.constants
   *
   * Below this doc block constants will be inserted by PhpStratum.
   */
  public const int CMP_ID_PLAISIO = 2;
  public const int CMP_ID_SYS     = 1;
  public const int LAN_ID_EN      = 1;
  public const int LAN_ID_NL      = 2;

  //--------------------------------------------------------------------------------------------------------------------
}

//----------------------------------------------------------------------------------------------------------------------
