<?php
declare(strict_types=1);

namespace Plaisio\Session\Test;

use Plaisio\Babel\Babel;
use Plaisio\Babel\CoreBabel;
use Plaisio\C;
use Plaisio\CompanyResolver\CompanyResolver;
use Plaisio\CompanyResolver\UniCompanyResolver;
use Plaisio\Cookie\CookieJar;
use Plaisio\LanguageResolver\CoreLanguageResolver;
use Plaisio\LanguageResolver\LanguageResolver;
use Plaisio\PlaisioKernel;
use SetBased\Stratum\MySql\MySqlDefaultConnector;

/**
 * Kernel for testing purposes.
 */
class TestKernelSys extends PlaisioKernel
{
  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the helper object for deriving the company.
   *
   * @return CompanyResolver
   */
  public function getCompany(): CompanyResolver
  {
    return new UniCompanyResolver(C::CMP_ID_SYS);
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the helper object for retrieving linguistic entities.
   *
   * @return Babel
   */
  protected function getBabel(): Babel
  {
    $babel = new CoreBabel($this);
    $babel->setLanguage(C::LAN_ID_EN);

    return $babel;
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the cookie jar.
   *
   * @return CookieJar
   */
  protected function getCookie(): CookieJar
  {
    return new CookieJar($_COOKIE);
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the data layer generated by PhpStratum.
   *
   * @return TestDataLayer
   */
  protected function getDL(): TestDataLayer
  {
    $connector = new MySqlDefaultConnector('localhost', 'test', 'test', 'test');
    $dl        = new TestDataLayer($connector);
    $dl->connect();
    $dl->begin();
    $dl->executeNone('delete from ABC_AUTH_SESSION');
    $dl->executeNone('delete from ABC_AUTH_SESSION_NAMED');
    $dl->executeNone('delete from ABC_AUTH_SESSION_NAMED_LOCK');
    $dl->commit();

    return $dl;
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * @return LanguageResolver
   */
  protected function getLanguageResolver(): LanguageResolver
  {
    return new CoreLanguageResolver($this, C::LAN_ID_EN);
  }

  //--------------------------------------------------------------------------------------------------------------------
}

//----------------------------------------------------------------------------------------------------------------------
